name: BuildersWand
author: Wythe
version: 2.5.0
main: de.False.BuildersWand.Main
softdepend: [ASkyBlock, WorldGuard, Towny, GriefPrevention, Factions, mcMMO]
commands:
  builderswand:
    description: The general BuildersWand command.
    usage: /builderswand
    aliases: [bw]