wand:
  name: "&3Builders Wand"
  material: "BLAZE_ROD"
  maxSize: 8
  consumeItems: true
crafting:
  enabled: true
  shapeless: true
  recipe:
    - "xxd"
    - "xbx"
    - "bxx"
  ingredient:
    d: "DIAMOND"
    b: "BLAZE_ROD"
particles:
  enabled: true
  type: "REDSTONE"
  count: 3
other:
  usePlayerLocale: true
  locale: "en_us"
