################################
#      Item information        #
################################
wand:
  name: "&3Builders Wand"
  material: "BLAZE_ROD"

################################
#    Custom crafting recipe    #
################################
crafting:
  enabled: true
  shapeless: true
  recipe:
    - "xxd"
    - "xbx"
    - "bxx"
  ingredient:
    d: "DIAMOND"
    b: "BLAZE_ROD"

################################
#           Particles          #
################################
particles:
  enabled: true
  type: "REDSTONE"
  count: 3

#################################################################################
#                                 Other options                                 #
#                                                                               #
#   consumeItems:                                                               #
#     Should the placed blocks consumed ?                                       #
#                                                                               #
#   usePlayerLocale:                                                            #
#     Use the configured locale (in minecraft) of the player?                   #
#                                                                               #
#   locale:                                                                     #
#     The locale which will used when usePlayerLocale is false.                 #
#                                                                               #
#################################################################################
other:
  consumeItems: true
  usePlayerLocale: true
  locale: "en_us"
