name: BuildersWand
author: Wythe
version: 1.4.0
main: de.False.BuildersWand.BuildersWand
softdepend: [ASkyBlock, WorldGuard]
commands:
  builderswand:
    description: The general BuildersWand command.
    usage: /builderswand
    aliases: [bw]