name: BuildersWand
author: Wythe
version: 2.3.3
main: de.False.BuildersWand.Main
softdepend: [ASkyBlock, WorldGuard, Towny, GriefPrevention]
commands:
  builderswand:
    description: The general BuildersWand command.
    usage: /builderswand
    aliases: [bw]