name: BuildersWand
author: Wythe
version: 2.0.0
main: de.False.BuildersWand.Main
softdepend: [ASkyBlock, WorldGuard]
commands:
  builderswand:
    description: The general BuildersWand command.
    usage: /builderswand
    aliases: [bw]